using System.ComponentModel;
using System.Windows.Media;

/* this class represents the object that is used to mount the UI of the program*/
public class OptionsMonitored : INotifyPropertyChanged
{

    public event PropertyChangedEventHandler? PropertyChanged;

    protected void OnPropertyChanged(string name)
    {
        PropertyChanged?.Invoke(
            this,
            new PropertyChangedEventArgs(name));
    }

    // All the options will grouped by strike
    public decimal Strike { get; set; }

    // CALL
    public string? CallCodigo { get; set; }

    // topic is the identifier that the RTD server uses to update the data of the option,
    // it is generated when the RTD server receives the request to monitor a new option,
    // and it is used to identify which option should be updated when the RTD server receives new data.
    // The topic is generated by the RTD server and returned to the client when the client requests to monitor a new option,
    // so it is important to store it in this class to be able to update the correct option when new data arrives.
    public Dictionary<string, string> CallParameters { get; set; } = new();
    // Here are storaged all the keys that should be monitored by the RTD 

    public Dictionary<string, string> CallTopics { get; set; } = new();
    // PUT
    public string? PutCodigo { get; set; }

    // topic is the identifier that the RTD server uses to update the data of the option,
    // it is generated when the RTD server receives the request to monitor a new option,
    // and it is used to identify which option should be updated when the RTD server receives new data.
    // The topic is generated by the RTD server and returned to the client when the client requests to monitor a new option,
    // so it is important to store it in this class to be able to update the correct option when new data arrives.
    public Dictionary<string, string> PutParameters { get; set; } = new();

    public Dictionary<string, string> PutTopics { get; set; } = new();

    // Here are storaged all the keys that should be monitored by the RTD 

    public bool IsAlert { get; set; } = false;

    public Brush AlertBrush { get; set; } = Brushes.Transparent;

    public void UpdateCallParameter(
    string key,
    string value)
    {
        CallParameters[key] = value;

        OnPropertyChanged(nameof(CallParameters));
    }

    public void UpdatePutParameter(
    string key,
    string value)
    {
        PutParameters[key] = value;

        OnPropertyChanged(nameof(PutParameters));
    }

    public void UpdateAlertStatus(bool isAlert, Brush alertBrush)
    {
        IsAlert = isAlert;
        AlertBrush = alertBrush;
        OnPropertyChanged(nameof(IsAlert));
        OnPropertyChanged(nameof(AlertBrush));
    }
}
